layout: page
#title: 'c0rvu5'
theme: jekyll-theme-hacker
permalink: /test.md
permalink: /access_control_vulnerabilities.md
permalink: /authentication_vulnerabilities.md
permalink: /business_logic_vulnerabilities.md
#theme: jekyll-theme-hacker
permalink: /clickjacking.md
permalink: /command_injection.md
permalink: /cross_origin_resource_sharing_CORS.md
permalink: /cross_site_request_forgery_CSRF.md
permalink: /directory_traversal.md
permalink: /DOM_based_vulnerabilities.md
permalink: /file_upload_vulnerabilities.md
permalink: /HTTP_host_header_vulnerabilities.md
permalink: /HTTP_request_smuggling.md
permalink: /information_disclosure_vulnerabilities.md
permalink: /insecure_deserialization.md
permalink: /JWT_attacks.md
permalink: /OAuth_authentication.md
permalink: /server_side_request_forgery_SSRF.md
permalink: /server_side_template_injection_SSTI.md
permalink: /SQLi.md
permalink: /web_cache_poisoning.md
