layout: page
#title: 'c0rvu5'
permalink: /test.md
permalink: /access_control_vulnerabilities.md
permalink: /authentication_vulnerabilities.md
permalink: business_logic_vulnerabilities.md
theme: jekyll-theme-hacker
permalink: clickjacking.md
permalink: command_injection.md
